spring.application.name=order-service

server.port=8089


# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/shopway_order
spring.datasource.username=lipsapriyadarsanidhal
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

